name: Go CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Added
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Test
      run: go test ./...
    - name: Build
      run: go build -v -o ./server ./cmd/server/main.go
    # The 'Run' step that was here is now removed.
